---
- name: "Converge"
  hosts: all
  become: true
  vars:
    - ansible_role_locale_locales:
        - language: hu
          variant: HU
        - language: en
          variant: US

  roles:
    - lordoftheflies.ansible_role_locale

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false